-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE public.industries
--   ADD CONSTRAINT industries_value_fkey
--   FOREIGN KEY (value) REFERENCES public.industries_enum(value);
